// app/components/commons/ToggleSwitch.vue
<script setup lang="ts">
/**
 * @component ToggleSwitch
 * @description 移动端开关组件（替代 Radix Switch）
 * @author gouxinjie
 * @created 2026-08-10
 */

const props = withDefaults(
  defineProps<{
    checked: boolean;
    disabled?: boolean;
    ariaLabel: string;
  }>(),
  {
    disabled: false,
  },
);

const emit = defineEmits<{
  (e: "update:checked" | "change", value: boolean): void;
}>();

/** 切换开关 */
function handleChange() {
  const next = !props.checked;
  emit("update:checked", next);
  emit("change", next);
}
</script>

<template>
  <button
    type="button"
    role="switch"
    :aria-checked="props.checked"
    :aria-label="props.ariaLabel"
    :disabled="props.disabled"
    :class="[
      'relative h-7 w-12 shrink-0 rounded-full border transition-colors duration-200 ease-out outline-none focus-visible:ring-2 focus-visible:ring-[#B9EDE2] focus-visible:ring-offset-2 focus-visible:ring-offset-white disabled:cursor-not-allowed disabled:opacity-60',
      props.checked
        ? 'border-[#3D9428] bg-[#5EBF3F]'
        : 'border-[#D8DADF] bg-[#D8DADF]',
    ]"
    @click="handleChange"
  >
    <span
      :class="[
        'block h-6 w-6 rounded-full bg-white shadow-[0_1px_3px_rgba(0,0,0,0.22)] transition-transform duration-200 ease-out will-change-transform',
        props.checked ? 'translate-x-[22px]' : 'translate-x-[2px]',
      ]"
    />
  </button>
</template>

// src/components/commons/toggle-switch.tsx
﻿"use client";

/**
 * @component ToggleSwitch
 * @description 基于 Radix Switch 的移动端开关组件
 * @author gouxinjie
 * @created 2026-06-26
 * @updated 2026-06-26
 */
import * as Switch from "@radix-ui/react-switch";

import { cn } from "@/lib/cn";

interface ToggleSwitchProps {
  checked: boolean;
  disabled?: boolean;
  ariaLabel: string;
  onCheckedChange: (checked: boolean) => void;
}

export function ToggleSwitch({
  checked,
  disabled = false,
  ariaLabel,
  onCheckedChange,
}: ToggleSwitchProps) {
  return (
    <Switch.Root
      checked={checked}
      disabled={disabled}
      aria-label={ariaLabel}
      onCheckedChange={onCheckedChange}
      className={cn(
        "relative h-7 w-12 shrink-0 rounded-full border transition-colors duration-200 ease-out outline-none",
        "data-[state=checked]:border-[#3D9428] data-[state=checked]:bg-[#5EBF3F]",
        "data-[state=unchecked]:border-[#D8DADF] data-[state=unchecked]:bg-[#D8DADF]",
        "focus-visible:ring-2 focus-visible:ring-[#B9EDE2] focus-visible:ring-offset-2 focus-visible:ring-offset-white",
        "disabled:cursor-not-allowed disabled:opacity-60",
      )}
    >
      <Switch.Thumb
        className={cn(
          "block h-6 w-6 rounded-full bg-white shadow-[0_1px_3px_rgba(0,0,0,0.22)] transition-transform duration-200 ease-out will-change-transform",
          "translate-x-[2px] data-[state=checked]:translate-x-[22px]",
        )}
      />
    </Switch.Root>
  );
}
